# Generated by Django 4.2.24 on 2025-12-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('weather', models.CharField(choices=[('SUNNY', 'Sunny'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy'), ('SNOWY', 'Snowy')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('google_map_link', models.URLField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations_app.touristdestination')),
            ],
        ),
    ]
