# Generated by Django 4.2.24 on 2025-12-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationimage',
            old_name='image',
            new_name='destination_img',
        ),
    ]
