# Generated by Django 4.2.24 on 2025-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_app', '0002_rename_image_destinationimage_destination_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='destination_img',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
